name: Frontend CI/CD

on:
    push:
        branches: ["main"]
        paths:
            - 'frontend/**'
            - '.github/workflows/frontend_run.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: checkout the code
             uses: actions/checkout@v4
           - name: Set up Nodejs
             uses: actions/setup-node@v4
             with:
                node-version: '24'
           - name: Install Dependency
             working-directory: ./frontend
             run: npm ci 
           - name: Run Lint
             working-directory: ./frontend
             run: npm run lint  
           - name: build frontend
             working-directory: ./frontend
             run: npm run build
           - name: check build status 
             if: failure()
             run: exit 1

    deployment:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  working-directory: ./frontend
                  vercel-args: '--prod'